
module.exports = {
    USER_COLLECTIONS: 'User',
    PRODUCT_COLLECTIONS: 'Product',
    CATEGORY_COLLECTIONS: 'Category',
    BRANDS_COLLECTIONS: 'Brands',
    ADMIN_COLLECTIONS: 'Admin',
    CART_COLLECTIONS: 'Cart',
    ORDER_COLLECTIONS: 'Order',
    ADDRESS_COLLECTIONS: 'Address',
    COUPON_COLLECTIONS: 'Coupon',
    OFFER_COLLECTIONS: 'Offer',
    PRODUCTOFFER_COLLECTIONS: 'ProductOffer',
    ORDERPRODUCT_COLLECTIONS: 'OrderProduct',
    TWILIO_ACCOUNT_SID: 'AC83df1d0b337a8516ad9640b33a458a11',
    TWILIO_TOKEN: '66bb9d426bff21fb63fa4703e1b42f3c',
    TWILIO_SERVICE_ID: 'VA10e44b2b3cd6f1721cef7743c3c58f8b'


}